appId = "0x416e7a656e5072696d6550726f6f6631"

[appName]
en = "Anzen Proof"

[permissions]
template = ["gui-app"]
"os/fs" = [
    "CloseFile",
    "Flush",
    "GetUsbReadAccess",
    "GetUsbWriteAccess",
    "OpenFileMessage",
    "ReadFile",
    "Rename",
    "TruncateFile",
    "WriteFile",
]
"os/security" = ["GetAppSeed", "GetRandom"]
